name: build
on: [push, pull_request]
jobs:

  ros1:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:noetic-ros-base-focal
    steps:
    - name: non-ros-deps
      run: |
        sudo apt update && sudo apt install \
          git wget \
          python3-rosdep \
          python3-vcstool \
          python3-colcon-common-extensions \
          maven default-jdk -y
    - name: workspace
      run: |
        mkdir -p ros1_ws/src
        cd ros1_ws/src
        git clone https://github.com/osrf/free_fleet
        git clone https://github.com/osrf/rmf_core
        git clone https://github.com/eclipse-cyclonedds/cyclonedds
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ros1_ws/src/free_fleet
    - name: ros-deps
      run: |
        cd ros1_ws
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro noetic -yr
    - name: build
      shell: bash
      run: |
        cd ros1_ws
        source /opt/ros/noetic/setup.bash
        colcon build \
          --cmake-args -DCMAKE_BUILD_TYPE=RELEASE \
          --packages-ignore ament_cmake_catch2 rmf_cmake_uncrustify \
          --packages-up-to free_fleet free_fleet_cyclonedds

  ros2:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy-ros-base-focal
    steps:
    - name: non-ros-deps
      run: |
        sudo apt update && sudo apt install \
          git wget \
          python3-rosdep \
          python3-vcstool \
          python3-colcon-common-extensions
    - name: workspace
      run: |
        mkdir -p ros2_ws/src
        cd ros2_ws/src
        git clone https://github.com/osrf/free_fleet
        git clone https://github.com/osrf/rmf_core
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ros2_ws/src/free_fleet
    - name: ros-deps
      run: |
        cd ros2_ws
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro foxy -yr
    - name: build
      shell: bash
      run: |
        cd ros2_ws
        source /opt/ros/foxy/setup.bash
        colcon build \
          --cmake-args -DCMAKE_BUILD_TYPE=RELEASe \
          --packages-up-to free_fleet free_fleet_cyclonedds
