name: build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:
    name: build 
    runs-on: ubuntu-20.04
    steps:
    - name: pwd
      run: pwd
    - name: deps
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: galactic 
    - name: build
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        target-ros2-distro: galactic 
        package-name: |
          free_fleet
          free_fleet_cyclonedds
        vcs-repo-file-url: |
          https://raw.githubusercontent.com/open-rmf/free_fleet/main/ff.repos
